name: Android Build

concurrency:
  group: android_build
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"

jobs:
  build_apk:
    strategy:
      matrix:
        include:
          - mode: all

    name: Build APK for ${{ matrix.mode }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Build the Artifact
        run: |
          gradle :app-debug:build 

      - name: Upload the Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.mode }}
          path: app-debug/build/outputs/apk/release/*.apk